"""
prepare.py — Frozen evaluator for the ml-loop Karpathy example.

DO NOT EDIT THIS FILE. It is the frozen evaluator by contract. The dataset,
split, and evaluation metric are fixed across all experiments so that results
from different runs of train.py are directly comparable.

Dataset:
  1000 samples, 10 features, binary classification.
  Labels are a deterministic nonlinear function of X:
    y = 1  if  (x0*x1 + 0.5*x2 + noise) > 0
    y = 0  otherwise
  A linear model achieves ~68-72% accuracy.
  A well-tuned nonlinear model can reach ~85-90%.
  There is real learnable signal here.

Public API:
  get_dataset() -> (X_train, y_train, X_val, y_val)
      X_* : list[list[float]]  — shape (N, 10)
      y_* : list[int]          — 0 or 1

  accuracy(y_true, y_pred) -> float
      Returns fraction of correct predictions in [0.0, 1.0].
"""

from __future__ import annotations

import math
import random

# ── Seeds (never change these) ────────────────────────────────────────────────
_DATASET_SEED = 1337
_SPLIT_SEED   = 1338

# ── Dataset generation ────────────────────────────────────────────────────────

def _lcg(state: int) -> tuple[int, float]:
    """Minimal LCG RNG — returns (new_state, float in [0,1))."""
    state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
    return state, state / 0x100000000


def _randn_pair(state: int) -> tuple[int, float, float]:
    """Box-Muller transform: two standard-normal samples from LCG state."""
    state, u1 = _lcg(state)
    state, u2 = _lcg(state)
    # Avoid log(0)
    u1 = max(u1, 1e-12)
    r = math.sqrt(-2.0 * math.log(u1))
    theta = 2.0 * math.pi * u2
    return state, r * math.cos(theta), r * math.sin(theta)


def _generate_dataset() -> tuple[list[list[float]], list[int]]:
    state = _DATASET_SEED
    X: list[list[float]] = []
    y: list[int] = []

    for _ in range(1000):
        row: list[float] = []
        for _ in range(5):               # 5 pairs → 10 features
            state, a, b = _randn_pair(state)
            row.append(a)
            row.append(b)
        X.append(row)

        # Nonlinear label: y = 1 if (x0*x1 + 0.5*x2 + noise) > 0
        state, noise, _ = _randn_pair(state)
        noise *= 0.1
        logit = row[0] * row[1] + 0.5 * row[2] + noise
        y.append(1 if logit > 0 else 0)

    return X, y


def get_dataset() -> tuple[
    list[list[float]], list[int],
    list[list[float]], list[int],
]:
    """
    Returns (X_train, y_train, X_val, y_val).

    80/20 train/val split, fixed seed. Every call returns the same data.
    """
    X, y = _generate_dataset()
    n = len(X)
    indices = list(range(n))

    rng = random.Random(_SPLIT_SEED)
    rng.shuffle(indices)

    split = int(0.8 * n)
    train_idx = indices[:split]
    val_idx   = indices[split:]

    X_train = [X[i] for i in train_idx]
    y_train = [y[i] for i in train_idx]
    X_val   = [X[i] for i in val_idx]
    y_val   = [y[i] for i in val_idx]

    return X_train, y_train, X_val, y_val


# ── Evaluation metric ─────────────────────────────────────────────────────────

def accuracy(y_true: list[int], y_pred: list[int]) -> float:
    """Fraction of predictions that match ground truth. Higher is better."""
    if not y_true:
        raise ValueError("Empty label list.")
    correct = sum(1 for a, b in zip(y_true, y_pred) if a == b)
    return correct / len(y_true)
